# Generated by Django 4.1.3 on 2022-11-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cmsslider_cms_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_title',
            field=models.CharField(max_length=120, verbose_name='Заголовок'),
        ),
    ]
