# Generated by Django 4.1.3 on 2022-11-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_Dt', models.DateTimeField(auto_now=True)),
                ('order_name', models.CharField(max_length=200)),
                ('orders_phone', models.CharField(max_length=200)),
            ],
        ),
    ]
